hl7-consumer: mllp-server

mllp-server:
  listen-port: 8904
  listen-address: localhost

run-handlers:
  - ack-handler

ack-handler:
  ack-aa: 0.0
  ack-ae: 1.0
  ack-ar: 0.0
  filename: log/app4-ack.log
