hl7-consumer: dir-client

dir-client:
  dir-path: files/hl7
  filename-pattern: ".*?[.]hl7"

run-handlers:
  - logger-handler
  - terser-logger-handler

logger-handler:
  filename: log/app11-log.log

terser-logger-handler:
  filename: log/app11-tersers.log
  tersers:
    - MSH-9-2
    - PID-18