hl7-consumer: mllp-server

mllp-server:
  listen-port: 8907
  listen-address: localhost

run-handlers:
  - ack-handler

ack-handler:
  ack-aa: 0.0
  ack-ae: 0.5
  ack-ar: 0.5
  filename: log/app7-ack.log
