hl7-consumer: mllp-server

mllp-server:
  listen-port: 8888
  listen-address: localhost

run-handlers:
  - ack-handler

ack-handler:
  ack-aa: 1.0
  ack-ae: 0.2
  ack-ar: 0.3
  filename: log/err1-ack.log
