hl7-consumer: mllp-server

mllp-server:
  listen-port: 8905
  listen-address: localhost

run-handlers:
  - wait-handler
  - ack-handler

wait-handler:
  delay: 10
  scope: 1.0
  filename: log/app5-wait.log

ack-handler:
  ack-aa: 1.0
  ack-ae: 0.0
  ack-ar: 0.0
  filename: log/app5-ack.log
