hl7-consumer: mllp-server

mllp-server:
  listen-port: 8903
  listen-address: localhost

run-handlers:
  - ack-handler

ack-handler:
  ack-aa: 0.6
  ack-ae: 0.2
  ack-ar: 0.2
  filename: log/app3-ack.log
